### ISSUE TITLE
Error checker line numbers overlap

### ISSUE THREAD

**Issue by crosjef** [paul-go/Truth#4]
The line numbers in the error list are all overlapping in the bottom right so I can't read any of them.

<img width="195" alt="Screen Shot 2019-03-20 at 1 52 56 PM" src="https://user-images.githubusercontent.com/47988612/54707443-7cb3cd00-4b17-11e9-9f69-6c1224813bbf.png">

**Comment by paul-go** [comment]
Fixed in the latest build.

**Comment by crosjef** [comment]
Verified
<img width="198" alt="Screen Shot 2019-05-09 at 10 08 36 AM" src="https://user-images.githubusercontent.com/47988612/57460074-72be6880-7242-11e9-9e9b-06d9258987bc.png">
